apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      containers:
        - name: express-server
          image: mytestacr001-e3dnf6bsc3gmckah.azurecr.io/express-server:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: express-server-service
spec:
  type: LoadBalancer
  selector:
    app: express-server
  ports:
    - port: 80
      targetPort: 3000